version: '3'

services:
  postgres:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    #command: start --db=postgres --db-url-host=postgres --db-username=keycloak --db-password=password --db-schema=public --http-relative-path=/auth --hostname-strict=false --import-realm
    command: 
      start-dev 
      --db=postgres 
      --db-url-host=postgres 
      --db-username=keycloak 
      --db-password=password 
      --db-schema=public 
      --http-relative-path=/auth 
      --hostname-strict=false
      --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./config_realms:/opt/keycloak/data/import
    depends_on:
      - postgres

volumes:
  postgres_data: